name: Browser-based Visualization Tests

on:
  workflow_dispatch:  # Manual trigger only

jobs:
  browser-tests:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install -e .[viz-test]
        playwright install chromium
    
    - name: Run UI visualization tests
      run: |
        pytest tests/ui/test_browser_viz.py -v
    
    - name: Upload test screenshots (on failure)
      if: failure()
      uses: actions/upload-artifact@v3
      with:
        name: test-screenshots
        path: |
          tests/ui/screenshots
          tests/ui/diff-*.png
        if-no-files-found: ignore